services:
  orly-airpark-mockup:
    image: ghcr.io/m6o4solutions/orly-airpark-mockup:latest
    container_name: orly-airpark-mockup
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orly-airpark-mockup.rule=Host(`mockup.orly-airpark.com`)"
      - "traefik.http.routers.orly-airpark-mockup.entrypoints=websecure"
      - "traefik.http.routers.orly-airpark-mockup.tls.certresolver=letsencrypt"
      - "traefik.http.services.orly-airpark-mockup.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
    name: traefik-network
