services:
  mockup-template:
    image: ghcr.io/m6o4solutions/mockup-template:latest
    container_name: mockup-template
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mockup-template.rule=Host(`mockup-template.m6o4solutions.com`)"
      - "traefik.http.routers.mockup-template.entrypoints=websecure"
      - "traefik.http.routers.mockup-template.tls.certresolver=letsencrypt"
      - "traefik.http.services.mockup-template.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
    name: traefik-network
